Added unit test to the workflow

diff --git a/python/fastAPI/template/.github/workflows/cicd.yaml b/python/fastAPI/template/.github/workflows/cicd.yaml
--- a/python/fastAPI/template/.github/workflows/cicd.yaml
+++ b/python/fastAPI/template/.github/workflows/cicd.yaml
@@ -11,6 +11,40 @@ jobs:
   ci:
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout source code
+        uses: actions/checkout@v3    
+      - name: Install dependencies
+        run: |
+          pip install -r requirements.txt
+          pip install pytest==8.4.1 pytest-mock==3.14.1 asynctest==0.13.0 dotenv==0.9.9 pytest-asyncio==1.1.0
+      - name: Install xmllint
+        run: sudo apt-get install -y libxml2-utils          
+      - name: Run Unit Tests and Generate Report
+        run: |
+          pytest tests/unit \
+            --cov=my_package \
+            --cov-fail-under=70 \
+            --junitxml=results.xml
+      - name: Upload reports
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-reports
+          path: |
+            results.xml
+            coverage.xml          
+      - name: Fail if <95% test cases passed
+        run: |
+          total=$(xmllint --xpath 'string(count(//testcase))' results.xml)
+          failed=$(xmllint --xpath 'string(count(//testcase[failure]))' results.xml)
+          passed=$((total - failed))
+          percent=$((100 * passed / total))
+          echo "Total: $total, Passed: $passed, Failed: $failed, Percent Passed: $percent%"
+          if [ "$percent" -lt 95 ]; then
+            echo "❌ Test pass rate is below 95% ($percent%)"
+            exit 1
+          fi
+        shell: bash
       - name: Add COMMIT_ID env property with commit short sha
         run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> $GITHUB_ENV
       - name: Login to Docker Hub
